version: '3.9'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      ./.env.dev
    depends_on:
      - db
      - celery

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  redis:
    image: redis:alpine

  celery:
    build: .
    volumes:
      - .:/code
    links:
      - redis
    env_file:
      - ./.env.dev
    depends_on:
      - redis

volumes:
  postgres_data:

